### ISSUE TITLE
剪裁的图片，Orientation信息会丢失

### ISSUE THREAD

**Issue by ioshc** [Rogue24/JPCrop#1]
比如我一张原始图片是向左或向右的图片。加载在imageView中显示时会自动修正到竖直向上，剪裁之后，imageView上的图片就变成了向左或向右的图片了，orientation信息就丢失了

**Comment by Rogue24** [comment]
OK 下班回去修复

发自我的iPhone

在 2021年1月26日，上午10:52，ioshc <notifications@github.com> 写道：

﻿

比如我一张原始图片是向左或向右的图片。加载在imageView中显示时会自动修正到竖直向上，剪裁之后，imageView上的图片就变成了向左或向右的图片了，orientation信息就丢失了

**Comment by Rogue24** [comment]
裁剪出来的图片都是垂直向上的 一般传入照片都会先修正方向 可以看一下我的demo 我传入前都会先修正一下：image.fixOrientation()

发自我的iPhone

在 2021年1月26日，下午12:45，周 健平 <zhoujianping24@hotmail.com> 写道：

﻿ OK 下班回去修复

发自我的iPhone

在 2021年1月26日，上午10:52，ioshc <notifications@github.com> 写道：

﻿

比如我一张原始图片是向左或向右的图片。加载在imageView中显示时会自动修正到竖直向上，剪裁之后，imageView上的图片就变成了向左或向右的图片了，orientation信息就丢失了
