### ISSUE TITLE
出现两个问题，1.旋转之后，窄边没有填满裁剪框，2.修改裁剪比例后，图片无法拖到到底部，希望能改进一下

### ISSUE THREAD

**Issue by zhouzhuo810** [Rogue24/JPCrop#5]
下面附上截图和视频：

旋转前截图：
![IMG_0485](https://user-images.githubusercontent.com/15272555/185518639-7f2a2cbe-c80e-41ce-89b3-0e7407c30e47.jpg)

旋转后截图：
![IMG_0484](https://user-images.githubusercontent.com/15272555/185518628-f51a757f-4d8f-4454-bc0d-ef69d0187f2f.jpg)

调整比例视频：
https://user-images.githubusercontent.com/15272555/185518393-b70e4337-bcf7-42ab-ba5a-03267ab41b31.MP4

**Comment by Rogue24** [comment]
@zhouzhuo810 能看一下你的初始化方法吗

**Comment by zhouzhuo810** [comment]
> @zhouzhuo810 能看一下你的初始化方法吗

<img width="724" alt="image" src="https://user-images.githubusercontent.com/15272555/185725008-46703791-053c-45bd-893a-6bfe1569214e.png">

会不会是因为我设置了frame，又用了自动布局的原因？

**Comment by zhouzhuo810** [comment]
好像是初始化的frame和后面自动布局的frame大小不一致造成的，我改成一致就没这个问题了。
