### ISSUE TITLE
支持OC吗

### ISSUE THREAD

**Issue by hanklee9820** [Rogue24/JPCrop#9]
如何打包成Framework给OC调用呢

**Comment by Rogue24** [comment]
@TBoyLi 你可以改一下源码 添加@objcMembers修饰一下即可

**Comment by hanklee9820** [comment]
@Rogue24  作者大大能支持一下吗？里面好多枚举，@objcMembers 都不支持

**Comment by hanklee9820** [comment]
@Rogue24 感谢作者。已搞定。
